In [15]:
import pandas as pd

In [36]:
df = pd.read_csv(r"C:\workspace\Ko-Swipe-ML\data\preprocessing\관광지 추천시스템 Trainset_B.csv")
df1 = pd.read_csv(r"C:\workspace\Ko-Swipe-ML\data\preprocessing\관광지 추천시스템 Testset_B.csv")

In [39]:
df = df[["TRAVEL_ID", "VISIT_AREA_NM"]]
df1 = df1[["TRAVEL_ID", "VISIT_AREA_NM"]]

In [42]:
df = pd.concat([df, df1]).reset_index(drop=True)

In [44]:
df.to_csv(r"C:\workspace\Ko-Swipe-ML\data\preprocessing\followup_places.csv", index=False)

In [45]:
haeundae_visitors = df[df['VISIT_AREA_NM'].str.contains('광안리해수욕장')]['TRAVEL_ID'].unique()

In [46]:
other_visits_by_haeundae_visitors = df[df['TRAVEL_ID'].isin(haeundae_visitors)]
other_visits_by_haeundae_visitors

      TRAVEL_ID   VISIT_AREA_NM
19    b_b000076         광안리해수욕장
20    b_b000076         BIFF 광장
21    b_b000076             피아크
22    b_b000076  롯데프리미엄아울렛 동부산점
54    b_b000267           용두산공원
...         ...             ...
3117  f_f004955    신세계백화점 센텀시티점
3118  f_f004955         광안리해수욕장
3119  f_f004955        해운대 해수욕장
3120  f_f008768         광안리해수욕장
3123  f_f016095         광안리해수욕장

[1213 rows x 2 columns]

In [47]:
other_visits_excluding_haeundae = other_visits_by_haeundae_visitors[
    ~other_visits_by_haeundae_visitors['VISIT_AREA_NM'].str.contains('광안리해수욕장')
]
other_visits_excluding_haeundae

      TRAVEL_ID   VISIT_AREA_NM
20    b_b000076         BIFF 광장
21    b_b000076             피아크
22    b_b000076  롯데프리미엄아울렛 동부산점
54    b_b000267           용두산공원
55    b_b000267        해운대 해수욕장
...         ...             ...
3105  b_b001984           창비 부산
3113  b_b005029         흰여울문화마을
3115  b_b005539    롯데월드 어드벤처 부산
3117  f_f004955    신세계백화점 센텀시티점
3119  f_f004955        해운대 해수욕장

[889 rows x 2 columns]

In [48]:
popular_places_after_haeundae = other_visits_excluding_haeundae['VISIT_AREA_NM'].value_counts().reset_index()
popular_places_after_haeundae.columns = ['VISIT_AREA_NM', 'visit_count']

In [50]:
popular_places_after_haeundae

     VISIT_AREA_NM  visit_count
0         해운대 해수욕장           89
1          밀락 더 마켓           57
2          흰여울문화마을           47
3           부평깡통시장           34
4       해운대 블루라인파크           32
..             ...          ...
252         에지 993            1
253  부산 근현대 역사관 별관            1
254          오향 마족            1
255            피아크            1
256    BNK 부산은행 본점            1

[257 rows x 2 columns]

In [49]:
popular_places_after_haeundae['VISIT_AREA_NM'][:5].tolist()

['해운대 해수욕장', '밀락 더 마켓', '흰여울문화마을', '부평깡통시장', '해운대 블루라인파크']